import java.awt.Color;
import java.awt.Component;
import java.text.DecimalFormat;

import javax.swing.Icon;
import javax.swing.JOptionPane;

/*
 * CompoundCalculator.java
 *
 * Created on __DATE__, __TIME__
 */

/**
 *
 * @author  __USER__
 */
public class CompoundCalculator extends javax.swing.JFrame {
	double P=0, i=0, F=0;//F:复利终值 P:本金 i:利率
	int N=0, M=0,m=0;//N:利率获取时间的整数倍 M:复利次数 m:月数
	String output;
	int result;
	int action=0;

	/** Creates new form CompoundCalculator */
	public CompoundCalculator() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		jButton5 = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jButton6 = new javax.swing.JButton();
		jButton7 = new javax.swing.JButton();
		jTextField1 = new javax.swing.JTextField();
		jTextField2 = new javax.swing.JTextField();
		jTextField3 = new javax.swing.JTextField();
		jTextField4 = new javax.swing.JTextField();
		jButton8 = new javax.swing.JButton();
		jLabel6 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jButton1.setText("\u590d\u5229");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setText("\u5355\u5229");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jButton3.setText("\u672c\u91d1\u4f30\u7b97");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		jButton4.setText("\u5e74\u9650\u4f30\u7b97");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});

		jButton5.setText("\u5229\u7387\u4f30\u7b97");
		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton5ActionPerformed(evt);
			}
		});

		jLabel1.setText("\u672c\u91d1\uff1a");

		jLabel2.setText("\u5e74\u5229\u7387\uff08%\uff09\uff1a");

		jLabel3.setText("\u5b58\u5165\u5e74\u9650\uff1a");

		jLabel4.setText("\u5e74\u590d\u5229\u6b21\u6570\uff1a");

		jLabel5.setText("\u590d\u5229\u7ec8\u503c\uff1a");

		jButton6.setText("\u5b9a\u671f\u6295\u8d44");
		jButton6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton6ActionPerformed(evt);
			}
		});

		jButton7.setText("\u7b49\u989d\u672c\u606f\u8fd8\u6b3e");
		jButton7.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton7ActionPerformed(evt);
			}
		});

		jTextField1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField1ActionPerformed(evt);
			}
		});

		jButton8.setText("\u8f93\u51fa");
		jButton8.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton8ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addComponent(
																		jButton1)
																.addGap(18, 18,
																		18)
																.addComponent(
																		jButton2)
																.addGap(18, 18,
																		18)
																.addComponent(
																		jButton3)
																.addGap(18, 18,
																		18)
																.addComponent(
																		jButton4))
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jLabel4)
																				.addComponent(
																						jLabel2)
																				.addComponent(
																						jLabel1)
																				.addComponent(
																						jLabel3)
																				.addComponent(
																						jLabel5))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jLabel6,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						241,
																						Short.MAX_VALUE)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																												.addComponent(
																														jTextField2,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														241,
																														Short.MAX_VALUE)
																												.addComponent(
																														jTextField1,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														241,
																														Short.MAX_VALUE)))
																				.addComponent(
																						jTextField3,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						241,
																						Short.MAX_VALUE)
																				.addComponent(
																						jTextField4,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						241,
																						Short.MAX_VALUE)
																				.addComponent(
																						jButton8,
																						javax.swing.GroupLayout.Alignment.TRAILING))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		22,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addContainerGap())
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap(45, Short.MAX_VALUE)
								.addComponent(jButton5)
								.addGap(18, 18, 18)
								.addComponent(jButton6)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jButton7).addGap(23, 23, 23)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jButton4)
												.addComponent(jButton3)
												.addComponent(jButton2)
												.addComponent(jButton1))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jButton7)
												.addComponent(jButton5)
												.addComponent(jButton6))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel1)
												.addComponent(
														jTextField1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(14, 14, 14)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel2)
												.addComponent(
														jTextField2,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel3)
												.addComponent(
														jTextField3,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel4)
												.addComponent(
														jTextField4,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel5)
												.addComponent(
														jLabel6,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														17,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18).addComponent(jButton8)
								.addContainerGap(20, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {
		calculate();
	}



	public void calculate() {
	
        if (jTextField1.getText()!=null && jTextField2.getText() != null
                && jTextField3.getText() != null && jTextField4.getText() != null) {
        	
			if (action==1){
				try { 
		 P = Double.parseDouble(jTextField1.getText());
		 i = Double.parseDouble(jTextField2.getText());
		 N = Integer.parseInt(jTextField3.getText());
		 M = Integer.parseInt(jTextField4.getText());
		 if(P<=0){ 
             JOptionPane.showMessageDialog(null, "输入有误，请重新输入"); 
             P=0;
         } 
         if(i<=0){ 
             JOptionPane.showMessageDialog(null, "输入有误，请重新输入"); 
             i=0;
         }     
         if(N<=0){ 
             JOptionPane.showMessageDialog(null, "输入有误，请重新输入"); 
             N=0;
         } 
         if(M<=0){ 
             JOptionPane.showMessageDialog(null, "输入有误，请重新输入"); 
             M=0;
         }
				}catch (Exception e) { 
            JOptionPane.showMessageDialog(null, "请输入数据"); 
         } 
				
		 F = P*java.lang.StrictMath.pow(1+i/M*0.01,M*N);
		 output=""+F+"";
		 jLabel6.setText(output);
		
			}
			else if(action==2){
				try{
				 P = Double.parseDouble(jTextField1.getText());
				 i = Double.parseDouble(jTextField2.getText());
				 N = Integer.parseInt(jTextField3.getText());
				 if(P<=0){ 
		             JOptionPane.showMessageDialog(null, "输入有误，请重新输入");  
		             P=0;
		         } 
		         if(i<=0){ 
		             JOptionPane.showMessageDialog(null, "输入有误，请重新输入"); 
		             i=0;
		         }     
		         if(N<=0){ 
		             JOptionPane.showMessageDialog(null, "输入有误，请重新输入"); 
		             N=0;
		         } 
						}catch (Exception e) { 
		             // TODO: handle exception 
		             JOptionPane.showMessageDialog(null, "请输入数据"); 
		         } 

				 F=P+(P*i*0.01*N);
				 output=""+F+"";
				 jLabel6.setText(output);
			}
			else if(action==3){
				try{
				 F = Double.parseDouble(jTextField1.getText());
				 i = Double.parseDouble(jTextField2.getText());
				 N = Integer.parseInt(jTextField3.getText());
				 M = Integer.parseInt(jTextField4.getText());
				 if(F<=0){ 
		             JOptionPane.showMessageDialog(null, "输入有误，请重新输入");  
		             F=0;
		         } 
		         if(i<=0){ 
		             JOptionPane.showMessageDialog(null, "输入有误，请重新输入"); 
		             i=0;
		         }     
		         if(N<=0){ 
		             JOptionPane.showMessageDialog(null, "输入有误，请重新输入"); 
		             N=0;
		         } 
		         if(M<=0){ 
		             JOptionPane.showMessageDialog(null, "输入有误，请重新输入"); 
		             M=0;
		         }
						}catch (Exception e) { 
		             // TODO: handle exception 
		             JOptionPane.showMessageDialog(null, "请输入数据"); 
		         } 
				 P=F/java.lang.StrictMath.pow(1+i/M*0.01,M*N);
				 output=""+P+"";
				 jLabel6.setText(output);
			}
			else if(action==4){
				try{
				 P = Double.parseDouble(jTextField1.getText());
				 i = Double.parseDouble(jTextField2.getText());
				 M = Integer.parseInt(jTextField3.getText());
				 F = Double.parseDouble(jTextField4.getText());
				 if(P<=0){ 
		             JOptionPane.showMessageDialog(null, "输入有误，请重新输入");  
		             P=0;
		         } 
		         if(i<=0){ 
		             JOptionPane.showMessageDialog(null, "输入有误，请重新输入");
		             i=0;
		         }     
		         if(F<=0){ 
		             JOptionPane.showMessageDialog(null, "输入有误，请重新输入"); 
		             F=0;
		         } 
		         if(M<=0){ 
		             JOptionPane.showMessageDialog(null, "输入有误，请重新输入"); 
		             M=0;
		         }
						}catch (Exception e) { 
		             // TODO: handle exception 
		             JOptionPane.showMessageDialog(null, "请输入数据"); 
		         } 
				 N= (int) (Math.log(F/P)/Math.log(1+i/M*0.01)/M);
				 output=""+N+"";
				 jLabel6.setText(output);
			}
			else if(action==5){
				try{
				 P = Double.parseDouble(jTextField1.getText());
				 N = Integer.parseInt(jTextField2.getText());
				 M = Integer.parseInt(jTextField3.getText());
				 F = Double.parseDouble(jTextField4.getText());
				 if(P<=0){ 
		             JOptionPane.showMessageDialog(null, "输入有误，请重新输入");  
		             P=0;
		         } 
		         if(N<=0){ 
		             JOptionPane.showMessageDialog(null, "输入有误，请重新输入"); 
		             N=0;
		         }     
		         if(F<=0){ 
		             JOptionPane.showMessageDialog(null, "输入有误，请重新输入"); 
		             F=0;
		         } 
		         if(M<=0){ 
		             JOptionPane.showMessageDialog(null, "输入有误，请重新输入"); 
		             M=0;
		         }
						}catch (Exception e) { 
		             // TODO: handle exception 
		             JOptionPane.showMessageDialog(null, "请输入数据"); 
		         } 
				 i=(java.lang.StrictMath.pow(F/P,1.0/(M*N))-1)*M/0.01;
				 output=""+i+"";
				 jLabel6.setText(output);
			}
			else if(action==6){
				try{
				 P = Double.parseDouble(jTextField1.getText());
				 i = Double.parseDouble(jTextField2.getText());
				 N = Integer.parseInt(jTextField3.getText());
				 if(P<=0){ 
		             JOptionPane.showMessageDialog(null, "输入有误，请重新输入");  
		             P=0;
		         } 
		         if(i<=0){ 
		             JOptionPane.showMessageDialog(null, "输入有误，请重新输入"); 
		             i=0;
		         }   
		         if(N<=0){ 
		             JOptionPane.showMessageDialog(null, "输入有误，请重新输入"); 
		             N=0;
		         }
						}catch (Exception e) { 
		             // TODO: handle exception 
		             JOptionPane.showMessageDialog(null, "请输入数据"); 
		         } 
				 F=P*(1+(i*0.01))*(-1+java.lang.StrictMath.pow(1+(i*0.01),N))/(i*0.01);
				 output=""+F+"";
				 jLabel6.setText(output);
			}
			else if(action==7){
				try{
				 P = Double.parseDouble(jTextField1.getText());
				 i = Double.parseDouble(jTextField2.getText());
				 m = Integer.parseInt(jTextField3.getText());
				 if(P<=0){ 
		             JOptionPane.showMessageDialog(null, "输入有误，请重新输入");  
		             P=0;
		         } 
		         if(i<=0){ 
		             JOptionPane.showMessageDialog(null, "输入有误，请重新输入"); 
		             i=0;
		         }     
		         if(m<=0){ 
		             JOptionPane.showMessageDialog(null, "输入有误，请重新输入"); 
		             m=0;
		         }
						}catch (Exception e) { 
		             // TODO: handle exception 
		             JOptionPane.showMessageDialog(null, "输入有误，请重新输入"); 
		         } 
				 F=P*(1+(i*0.01/12))*(-1+java.lang.StrictMath.pow(1+(i*0.01/12),m))/(i*0.01/12);
				 output=""+F+"";
				 jLabel6.setText(output);
			}
			else if(action==8){
				try{
				 P = Double.parseDouble(jTextField1.getText());
				 i = Double.parseDouble(jTextField2.getText());
				 N = Integer.parseInt(jTextField3.getText());
				 M = Integer.parseInt(jTextField3.getText());
				 if(P<=0){ 
		             JOptionPane.showMessageDialog(null, "输入有误，请重新输入");  
		             P=0;
		         } 
		         if(i<=0){ 
		             JOptionPane.showMessageDialog(null, "输入有误，请重新输入"); 
		             i=0;
		         }     
		         if(N<=0){ 
		             JOptionPane.showMessageDialog(null, "输入有误，请重新输入"); 
		             N=0;
		         } 
		         if(M<=0){ 
		             JOptionPane.showMessageDialog(null, "输入有误，请重新输入"); 
		             M=0;
		         }
						}catch (Exception e) { 
		             // TODO: handle exception 
		            JOptionPane.showMessageDialog(null, "请输入数据"); 
		         } 
				 F = P*i*0.01/12*java.lang.StrictMath.pow((1.0+i/M*0.01/12),M*N*12)/(java.lang.StrictMath.pow(1.0+i*0.01/M/12,M*N*12)-1);
				 output=""+F+"";
				 jLabel6.setText(output);
			}
			else if(action==0){
				JOptionPane.showMessageDialog(null, "请输入数据"); 
			}
			}
        else {
        	
        	JOptionPane.showMessageDialog(null, "请输入数据"); 
        	
        }
        P=0; 
        i=0; 
        F=0;
        N=0; 
        M=0; 
        m=0;


	}

	private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {
		jLabel1.setText("贷款金额：");
		jLabel2.setText("年利率（%）：");
		jLabel3.setText("年限：");
		jLabel4.setText("年复利次数：");
		jLabel5.setText("等额本息还款额：");
		jTextField1.setText(null);
		jTextField2.setText(null);
		jTextField3.setText(null);
		jTextField4.setText(null);
		jTextField4.show();
		jLabel6.setText(null);
		action=8;
	}

	private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
	
		Object[] options ={ "年投资", "月投资" };  
		int a = JOptionPane.showOptionDialog(null, "请选择投资方式", "定额投资",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);  
		if(a==JOptionPane.YES_OPTION){
		jLabel1.setText("年投资金额：");
		jLabel2.setText("年利率（%）：");
		jLabel3.setText("定投年数：");
		jLabel4.setText(null);
		jLabel5.setText("终值：");
		jTextField1.setText(null);
		jTextField2.setText(null);
		jTextField3.setText(null);
		jTextField4.setText(null);
		jTextField4.hide();
		jLabel6.setText(null);
		action=6;
		}
		else{
		jLabel1.setText("月投资金额：");
		jLabel2.setText("年利率（%）：");
		jLabel3.setText("定投月数：");
		jLabel4.setText(null);
		jLabel5.setText("终值：");
		jTextField1.setText(null);
		jTextField2.setText(null);
		jTextField3.setText(null);
		jTextField4.setText(null);
		jTextField4.hide();
		jLabel6.setText(null);
		action=7;
		}
	}

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
		jLabel1.setText("本金：");
		jLabel2.setText("年利率（%）：");
		jLabel3.setText("年复利次数：");
		jLabel4.setText("复利终值：");
		jLabel5.setText("年限：");
		jTextField1.setText(null);
		jTextField2.setText(null);
		jTextField3.setText(null);
		jTextField4.setText(null);
		jTextField4.show();
		jLabel6.setText(null);
		action=4;
	}

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		jLabel1.setText("复利终值：");
		jLabel2.setText("年利率（%）：");
		jLabel3.setText("存入年限：");
		jLabel4.setText("年复利次数：");
		jLabel5.setText("本金：");
		jTextField1.setText(null);
		jTextField2.setText(null);
		jTextField3.setText(null);
		jTextField4.setText(null);
		jTextField4.show();
		jLabel6.setText(null);
		action=3;
	}

	@SuppressWarnings("deprecation")
	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		jLabel1.setText("本金：");
		jLabel2.setText("年利率（%）：");
		jLabel3.setText("存入年限：");
		jLabel4.setText(null);
		jLabel5.setText("终值：");
		jTextField1.setText(null);
		jTextField2.setText(null);
		jTextField3.setText(null);
		jTextField4.setText(null);
		jTextField4.hide();
		jLabel6.setText(null);
		action=2;

	}

	private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
		jLabel1.setText("本金：");
		jLabel2.setText("存入年限：");
		jLabel3.setText("年复利次数：");
		jLabel4.setText("复利终值：");
		jLabel5.setText("年利率（%）：");
		jTextField1.setText(null);
		jTextField2.setText(null);
		jTextField3.setText(null);
		jTextField4.setText(null);
		jTextField4.show();
		jLabel6.setText(null);
		action=5;
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		jLabel1.setText("本金：");
		jLabel2.setText("年利率（%）：");
		jLabel3.setText("存入年限：");
		jLabel4.setText("年复利次数：");
		jLabel5.setText("复利终值：");
		jTextField1.setText(null);
		jTextField2.setText(null);
		jTextField3.setText(null);
		jTextField4.setText(null);
		jTextField4.show();
		jLabel6.setText(null);
		action=1;

	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new CompoundCalculator().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton6;
	private javax.swing.JButton jButton7;
	private javax.swing.JButton jButton8;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	javax.swing.JLabel jLabel6;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField jTextField4;
	// End of variables declaration//GEN-END:variables

	
		 public double Compound(double P,double i,int N,int M){
		         F = P*java.lang.StrictMath.pow(1+i/M*0.01,M*N);
		        return F;    
		    }
		 public double Simple(double P,double i,int N){
			    F=P+(P*i*0.01*N);
		        return F;    
		    }
		 public double Principle(double F,double i,int N,int M){
			 P=F/java.lang.StrictMath.pow(1+i/M*0.01,M*N);
		        return P;    
		    }
		 public double Year(double P,double i,int M,double F){
			 N= (int) (Math.log(F/P)/Math.log(1+i/M*0.01)/M);
		        return N;    
		    }
		 public double Rate(double P,int N,int M,double F){
			 i=(java.lang.StrictMath.pow(F/P,1.0/(M*N))-1)*M/0.01;
		        return i;    
		    }
		 public double Yearinvest(double P,double i,int N){
			 F=P*(1+(i*0.01))*(-1+java.lang.StrictMath.pow(1+(i*0.01),N))/(i*0.01);
		        return F;    
		    }
		 public double Monthinvest(double P,double i,int m){
			 F=P*(1+(i*0.01/12))*(-1+java.lang.StrictMath.pow(1+(i*0.01/12),m))/(i*0.01/12);
		        return F;    
		    }
		 public double Repayment(double P,double i,int N,int M){
			 F = P*i*0.01/12*java.lang.StrictMath.pow((1.0+i/M*0.01/12),M*N*12)/(java.lang.StrictMath.pow(1.0+i*0.01/M/12,M*N*12)-1);
		        return F;    
		    }
		
	
		

}
	
